In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules

In [2]:
df = pd.read_csv(r'F:\pk\01_Data_science\ASSIGNMENTS\09_Association_rule\groceries.csv',
            header=None,sep=";")

#we have all the shop items in one transactino in single row

In [3]:
import numpy as np

In [4]:
#taking each rows as list with single item list

list_values=df.values.tolist()

In [5]:
#each row as item in list
list2=[]
for sublist in list_values:
    for item in sublist:
        list2.append(item)
        
#each row as list with grocery items
list3=[]
for i in list2:
    list3.append(i.split(","))
    
#list consisting of all grocery items 
final_list=[]
for sublist in list3:
    for item in sublist:
        final_list.append(item)
        
#list consisting of only uniqe grocery items
unique_item=[]
for x in final_list:
    if x not in unique_item:
        unique_item.append(x)

In [14]:
# creating a data frame with unique items as columns 

df2 = pd.DataFrame(columns=unique_item)

df3=df2.copy()

In [15]:
#Assigning 0 or 1 

for index, row in df.iterrows():
    items = str(row[0]).split(',')
    one_hot_encoding = np.zeros(len(unique_item),dtype=int)
    for item_name in items:
        for i,column in enumerate(df3.columns):
            if item_name == column:
                one_hot_encoding[i] = 1
    df3.at[index] = one_hot_encoding

# Transction encoder is fastest method to do all this.

In [18]:
df3.head()

,citrus fruit,semi-finished bread,margarine,ready soups,tropical fruit,yogurt,coffee,whole milk,pip fruit,cream cheese,...,baby food,pudding powder,tidbits,whisky,frozen fruits,bags,cooking chocolate,sound storage medium,kitchen utensil,preservation products
0,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df3.describe()

,citrus fruit,semi-finished bread,margarine,ready soups,tropical fruit,yogurt,coffee,whole milk,pip fruit,cream cheese,...,baby food,pudding powder,tidbits,whisky,frozen fruits,bags,cooking chocolate,sound storage medium,kitchen utensil,preservation products
count,9835,9835,9835,9835,9835,9835,9835,9835,9835,9835,...,9835,9835,9835,9835,9835,9835,9835,9835,9835,9835
unique,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
freq,9021,9661,9259,9817,8803,8463,9264,7322,9091,9445,...,9834,9812,9812,9827,9823,9831,9810,9834,9831,9833

In [28]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9835 entries, 0 to 9834
Columns: 169 entries, citrus fruit to preservation products
dtypes: object(169)
memory usage: 13.1+ MB

In [21]:
#EDA

import seaborn as sns
import matplotlib.pyplot as plt

In [109]:
nwdf = pd.DataFrame(df3.sum(),columns=['Purchased'])

In [116]:
nwdf['Not_purchased']=(9835 - nwdf['Purchased'])

In [121]:
sort_df = pd.DataFrame(nwdf.sort_values(by=['Purchased'],ascending=False))

In [122]:
sort_df

                       Purchased  Not_purchased
whole milk                2513.0         7322.0
other vegetables          1903.0         7932.0
rolls/buns                1809.0         8026.0
soda                      1715.0         8120.0
yogurt                    1372.0         8463.0
...                          ...            ...
bags                         4.0         9831.0
kitchen utensil              4.0         9831.0
preservation products        2.0         9833.0
baby food                    1.0         9834.0
sound storage medium         1.0         9834.0

[169 rows x 2 columns]

In [124]:
#top 50 pruchased items 

sort_df.head(50)

                          Purchased  Not_purchased
whole milk                   2513.0         7322.0
other vegetables             1903.0         7932.0
rolls/buns                   1809.0         8026.0
soda                         1715.0         8120.0
yogurt                       1372.0         8463.0
bottled water                1087.0         8748.0
root vegetables              1072.0         8763.0
tropical fruit               1032.0         8803.0
shopping bags                 969.0         8866.0
sausage                       924.0         8911.0
pastry                        875.0         8960.0
citrus fruit                  814.0         9021.0
bottled beer                  792.0         9043.0
newspapers                    785.0         9050.0
canned beer                   764.0         9071.0
pip fruit                     744.0         9091.0
fruit/vegetable juice         711.0         9124.0
whipped/sour cream            705.0         9130.0
brown bread                   638.0         9197.0
domestic eggs                 624.0         9211.0
frankfurter                   580.0         9255.0
margarine                     576.0         9259.0
coffee                        571.0         9264.0
pork                          567.0         9268.0
butter                        545.0         9290.0
curd                          524.0         9311.0
beef                          516.0         9319.0
napkins                       515.0         9320.0
chocolate                     488.0         9347.0
frozen vegetables             473.0         9362.0
chicken                       422.0         9413.0
white bread                   414.0         9421.0
cream cheese                  390.0         9445.0
waffles                       378.0         9457.0
salty snack                   372.0         9463.0
long life bakery product      368.0         9467.0
dessert                       365.0         9470.0
sugar                         333.0         9502.0
UHT-milk                      329.0         9506.0
hamburger meat                327.0         9508.0
berries                       327.0         9508.0
hygiene articles              324.0         9511.0
onions                        305.0         9530.0
specialty chocolate           299.0         9536.0
candy                         294.0         9541.0
misc. beverages               279.0         9556.0
frozen meals                  279.0         9556.0
oil                           276.0         9559.0
butter milk                   275.0         9560.0
specialty bar                 269.0         9566.0

In [125]:
#least 50 pruchased items 

sort_df.tail(50)

                        Purchased  Not_purchased
curd cheese                  50.0         9785.0
male cosmetics               45.0         9790.0
rum                          44.0         9791.0
ketchup                      42.0         9793.0
meat spreads                 42.0         9793.0
light bulbs                  41.0         9794.0
brandy                       41.0         9794.0
tea                          38.0         9797.0
specialty fat                36.0         9799.0
abrasive cleaner             35.0         9800.0
skin care                    35.0         9800.0
nuts/prunes                  33.0         9802.0
artif. sweetener             32.0         9803.0
canned fruit                 32.0         9803.0
syrup                        32.0         9803.0
nut snack                    31.0         9804.0
snack products               30.0         9805.0
fish                         29.0         9806.0
potato products              28.0         9807.0
cookware                     27.0         9808.0
bathroom cleaner             27.0         9808.0
soap                         26.0         9809.0
cooking chocolate            25.0         9810.0
pudding powder               23.0         9812.0
tidbits                      23.0         9812.0
organic sausage              22.0         9813.0
cocoa drinks                 22.0         9813.0
prosecco                     20.0         9815.0
flower soil/fertilizer       19.0         9816.0
ready soups                  18.0         9817.0
specialty vegetables         17.0         9818.0
organic products             16.0         9819.0
decalcifier                  15.0         9820.0
honey                        15.0         9820.0
cream                        13.0         9822.0
frozen fruits                12.0         9823.0
hair spray                   11.0         9824.0
rubbing alcohol              10.0         9825.0
liqueur                       9.0         9826.0
salad dressing                8.0         9827.0
whisky                        8.0         9827.0
make up remover               8.0         9827.0
toilet cleaner                7.0         9828.0
frozen chicken                6.0         9829.0
baby cosmetics                6.0         9829.0
bags                          4.0         9831.0
kitchen utensil               4.0         9831.0
preservation products         2.0         9833.0
baby food                     1.0         9834.0
sound storage medium          1.0         9834.0

In [146]:
frequent_itemsets= apriori(df3, min_support=0.03, use_colnames=True)
frequent_itemsets

      support                             itemsets
0   0.0827656                       (citrus fruit)
1   0.0585663                          (margarine)
2    0.104931                     (tropical fruit)
3    0.139502                             (yogurt)
4    0.058058                             (coffee)
..        ...                                  ...
58  0.0426029       (other vegetables, rolls/buns)
59  0.0327402             (other vegetables, soda)
60  0.0473818  (other vegetables, root vegetables)
61  0.0383325                   (soda, rolls/buns)
62   0.030605                (sausage, rolls/buns)

[63 rows x 2 columns]

In [147]:
rule = association_rules(frequent_itemsets, metric="lift", min_threshold=0.3)

rule_df = rule.iloc[::2].sort_values("lift", ascending=False).reset_index().drop(columns="index")

In [149]:
rule_df

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(other vegetables),(root vegetables),0.193493,0.108998,0.047382,0.244877,2.246605,0.026291,1.179941
1,(sausage),(rolls/buns),0.093950,0.183935,0.030605,0.325758,1.771048,0.013324,1.210344
2,(tropical fruit),(other vegetables),0.104931,0.193493,0.035892,0.342054,1.767790,0.015589,1.225796
3,(whole milk),(whipped/sour cream),0.255516,0.071683,0.032232,0.126144,1.759754,0.013916,1.062323
4,(whole milk),(root vegetables),0.255516,0.108998,0.048907,0.191405,1.756031,0.021056,1.101913
5,(other vegetables),(yogurt),0.193493,0.139502,0.043416,0.224383,1.608457,0.016424,1.109436
6,(tropical fruit),(whole milk),0.104931,0.255516,0.042298,0.403101,1.577595,0.015486,1.247252
7,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,0.020379,1.244132
8,(pip fruit),(whole milk),0.075648,0.255516,0.030097,0.397849,1.557043,0.010767,1.236375
9,(other vegetables),(whole milk),0.193493,0.255516,0.074835,0.386758,1.513634,0.025394,1.214013
10,(pastry),(whole milk),0.088968,0.255516,0.033249,0.373714,1.462587,0.010516,1.188729
11,(citrus fruit),(whole milk),0.082766,0.255516,0.030503,0.368550,1.442377,0.009355,1.179008
12,(yogurt),(rolls/buns),0.139502,0.183935,0.034367,0.246356,1.339363,0.008708,1.082825
13,(bottled water),(whole milk),0.110524,0.255516,0.034367,0.310948,1.216940,0.006126,1.080446
14,(whole milk),(rolls/buns),0.255516,0.183935,0.056634,0.221647,1.205032,0.009636,1.048452
15,(other vegetables),(rolls/buns),0.193493,0.183935,0.042603,0.220179,1.197047,0.007013,1.046477
16,(soda),(rolls/buns),0.174377,0.183935,0.038332,0.219825,1.195124,0.006258,1.046003
17,(other vegetables),(soda),0.193493,0.174377,0.032740,0.169207,0.970348,-0.001000,0.993776
18,(whole milk),(soda),0.255516,0.174377,0.040061,0.156785,0.899112,-0.004495,0.979136

In [150]:
## top 5 association rules with lift > 1

rule_df.head(5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(other vegetables),(root vegetables),0.193493,0.108998,0.047382,0.244877,2.246605,0.026291,1.179941
1,(sausage),(rolls/buns),0.093950,0.183935,0.030605,0.325758,1.771048,0.013324,1.210344
2,(tropical fruit),(other vegetables),0.104931,0.193493,0.035892,0.342054,1.767790,0.015589,1.225796
3,(whole milk),(whipped/sour cream),0.255516,0.071683,0.032232,0.126144,1.759754,0.013916,1.062323
4,(whole milk),(root vegetables),0.255516,0.108998,0.048907,0.191405,1.756031,0.021056,1.101913